import { request } from "@/lib/request";

// Key material generated by the API, handed back once and kept nowhere: a
// self-signed certificate for the name given, or a Reality or WireGuard key pair
// -- or, given a WireGuard private key, the public key that goes with it.
//
// A listener's TLS and a WireGuard route out both ask for it, so it is written
// once here rather than in either.
export interface Keypair {
    kind: string;
    privateKey?: string;
    publicKey?: string;
    certificate?: string;
}

export const generateKeypair = async (kind: "tls" | "reality" | "wireguard", options = "") => {
    return request.get<Keypair>(`/keypairs?${new URLSearchParams({ kind, options })}`);
};
