-- Everything a panel starts with: its tables, and the two routes out the first
-- generated configuration needs. Once a database has run it, a change to the
-- schema is a migration of its own numbered after it, never an edit here: an
-- installed panel does not run this file a second time.

-- Panel operators and the API tokens they issue.

CREATE TABLE users (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     text   NOT NULL,
    -- bcrypt hash. Sized for the hash, not for a password.
    password     text   NOT NULL,
    -- The secret an authenticator app derives its codes from, base32 as the
    -- app is given it. Empty is an account signed in to with its password
    -- alone, which is every account until its operator sets one up.
    totp_secret  text   NOT NULL DEFAULT '',
    -- Last successful sign-in, as "2006-01-02 15:04:05 <ip>".
    last_sign_in text   NOT NULL DEFAULT '',
    created_at   bigint NOT NULL DEFAULT 0
);

-- Signing in looks an account up by name, and two accounts sharing one would
-- make which of them you authenticated as depend on row order.
CREATE UNIQUE INDEX idx_users_username ON users (username);

CREATE TABLE tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text   NOT NULL DEFAULT '',
    token       text   NOT NULL,
    -- Unix time, or 0 for a token that does not expire.
    expiry      bigint NOT NULL DEFAULT 0,
    -- A token carries its owner's authority, so it does not outlive the owner.
    user_id     bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at  bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_tokens_token ON tokens (token);
CREATE INDEX idx_tokens_user_id ON tokens (user_id);

-- Subscribers: quota, expiry, and the traffic counted against them.

CREATE TABLE clients (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enable      boolean NOT NULL DEFAULT true,
    name        text    NOT NULL,
    -- Inbound ids this client may connect through, as a JSON array.
    inbounds    jsonb,
    -- Per-protocol identities the client authenticates with.
    config      jsonb,

    -- Quota in bytes; 0 is unlimited.
    volume      bigint  NOT NULL DEFAULT 0,
    -- Unix time; 0 never expires.
    expiry      bigint  NOT NULL DEFAULT 0,
    -- Traffic in the current period.
    up          bigint  NOT NULL DEFAULT 0,
    down        bigint  NOT NULL DEFAULT 0,
    -- Traffic from every period before this one, kept across a reset.
    total_up    bigint  NOT NULL DEFAULT 0,
    total_down  bigint  NOT NULL DEFAULT 0,

    -- "desc" and "group" are reserved words; the model maps onto these names.
    description text    NOT NULL DEFAULT '',
    group_name  text    NOT NULL DEFAULT '',
    remark      text    NOT NULL DEFAULT '',

    created_at  bigint  NOT NULL DEFAULT 0,
    online_at   bigint  NOT NULL DEFAULT 0,

    -- Hold the expiry clock until the client's first byte.
    delay_start boolean NOT NULL DEFAULT false,
    -- Restart the quota every reset_days days, at next_reset.
    auto_reset  boolean NOT NULL DEFAULT false,
    reset_days  integer NOT NULL DEFAULT 0,
    next_reset  bigint  NOT NULL DEFAULT 0
);

-- The name is the join key traffic is reported against and the id a
-- subscription is fetched by, so a duplicate would silently split one
-- subscriber's traffic across two rows.
CREATE UNIQUE INDEX idx_clients_name ON clients (name);

-- The panel lists clients by group.
CREATE INDEX idx_clients_group_name ON clients (group_name);

-- The deplete job scans for enabled clients every minute and is uninterested
-- in the disabled ones, which are the majority on a panel that has been
-- running a while.
CREATE INDEX idx_clients_enable ON clients (enable) WHERE enable;

-- Listeners clients connect to. Each carries its own TLS: the server half --
-- what the core terminates with, Reality included -- is the `tls` block among
-- its options, and the client half -- what a subscriber is handed to meet it --
-- sits under the same key in its out_json, beside the rest of what a client is
-- told.

CREATE TABLE inbounds (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type     text   NOT NULL,
    tag      text   NOT NULL,
    -- Addresses this inbound is reachable at, for building client links.
    addrs    jsonb,
    -- Overrides for what a generated client link says about this inbound.
    out_json jsonb,
    -- Every remaining core option for this inbound type, kept verbatim so a
    -- new core release needs no migration here.
    options  jsonb
);

-- The tag identifies the inbound in the generated core config and in every
-- traffic sample reported against it.
CREATE UNIQUE INDEX idx_inbounds_tag ON inbounds (tag);

-- Runtime options an operator changes from the panel. Everything needed to
-- start the process lives in configs/ instead.

CREATE TABLE settings (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key   text   NOT NULL,
    value text   NOT NULL DEFAULT ''
);

-- Settings are read and written by key. A duplicate would make the value you
-- get depend on row order, and the upsert on save depends on this index.
CREATE UNIQUE INDEX idx_settings_key ON settings (key);

-- Traffic buckets and the audit log.

CREATE TABLE stats (
    id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Start of the bucket, in unix seconds.
    date_time bigint  NOT NULL,
    -- 'inbound', 'outbound' or 'client'.
    resource  text    NOT NULL,
    tag       text    NOT NULL,
    -- true is up, false is down.
    direction boolean NOT NULL,
    traffic   bigint  NOT NULL DEFAULT 0
);

-- Samples arriving inside the same bucket are added onto the existing row.
-- This index is what ON CONFLICT targets; without it a reporting interval
-- shorter than the bucket multiplies the row count by the ratio between them.
CREATE UNIQUE INDEX idx_stats_bucket ON stats (resource, tag, date_time, direction);

-- date_time sits third in idx_stats_bucket, so that index cannot serve the
-- retention purge, which filters on date_time alone.
CREATE INDEX idx_stats_date_time ON stats (date_time);

CREATE TABLE changes (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time bigint NOT NULL,
    -- An operator's username, or the name of the job that made the change.
    actor     text   NOT NULL,
    -- The kind of object that changed, e.g. 'clients'.
    key       text   NOT NULL,
    -- What happened to it, e.g. 'new', 'edit', 'del', 'disable'.
    action    text   NOT NULL,
    -- Which object, and for an edit what it became.
    obj       jsonb
);

-- The audit view is newest-first, optionally narrowed to one actor or one kind
-- of object.
CREATE INDEX idx_changes_date_time ON changes (date_time DESC);
CREATE INDEX idx_changes_actor ON changes (actor);
CREATE INDEX idx_changes_key ON changes (key);

-- Routes out of the node, WireGuard tunnels among them, and the seed that makes
-- the first generated configuration a valid one.

CREATE TABLE outbounds (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type    text   NOT NULL,
    tag     text   NOT NULL,
    -- Every remaining core option for this outbound type, kept verbatim so a
    -- new core release needs no migration here.
    options jsonb
);

-- The tag identifies the outbound in the generated configuration, in every
-- route rule that detours to it, and in traffic reported against it.
CREATE UNIQUE INDEX idx_outbounds_tag ON outbounds (tag);

-- A configuration with inbounds and no outbounds routes nothing, so a fresh
-- install would generate a document the core refuses. Seeding `direct` means
-- the first generation is already valid; an operator who wants something else
-- can edit or delete it.
INSERT INTO outbounds (type, tag, options) VALUES ('direct', 'direct', '{}');

-- `block` refuses whatever is sent through it. A rule can refuse what it matches
-- with its own reject action, but what can only name a route out -- the default
-- outbound above all -- needs one to refuse with, and an operator reaching for
-- it should find it there as they find `direct`.
--
-- It goes in second, in a statement of its own, so it is never the first: the
-- core sends whatever no rule matched through the first route out unless the
-- base configuration names another, and a block route in first place would
-- refuse all of it.
INSERT INTO outbounds (type, tag, options) VALUES ('block', 'block', '{}');
