import { IconButton, InlineMessage } from "@gamecrafters/base-ui/react";
import { ArrowClockwiseRegular, KeyRegular } from "@gamecrafters/base-ui-icons";
import { useId, useState } from "react";

import { FilledListField, FilledTextInput } from "@/components/FilledField";
import { generateKeypair } from "@/lib/keypair";

import { peerOf, withPeer } from "../api";
import type { OutboundOptionIssue } from "../api/field-specs";

interface WireGuardFieldsProps {
    // The route's options, which the fields read off and hand back whole with one
    // of them changed.
    options: Record<string, unknown>;
    onChange: (options: Record<string, unknown>) => void;
    // Held still while the options they are read off cannot be read.
    disabled?: boolean;
    issue?: OutboundOptionIssue | null;
}

// A field's share of a row, the reference's: two thirds from a tablet up for a
// key or a list of addresses, half for the addresses a peer allows, and a third
// from a laptop up for the MTU.
const ROW = "grid grid-cols-12 gap-2";
const WIDE = "col-span-12 min-[600px]:col-span-8";
const HALF = "col-span-12 min-[600px]:col-span-6";
const FIELD = "col-span-12 min-[600px]:col-span-6 min-[840px]:col-span-4";

// The button standing after a field, as the reference's icon does.
const FIELD_ACTION = "size-6 min-w-0 p-0 text-[var(--foreground-color-muted)]";

const textOf = (value: unknown) => (typeof value === "string" ? value : "");

// A WireGuard route's own options, laid out as the reference laid out its
// WireGuard outbound while the core still took one: the tunnel's private key, the
// peer's public key and the key the two share, the addresses the tunnel holds,
// then those it sends down it and the size of what it sends. They are written the
// way the core takes them now, as an endpoint with one peer -- the far end, whose
// address and port are the route's server fields.
//
// The key pair is generated by the API, as the reference has it generated. The
// public half goes to whoever runs the far end, and the core has nowhere to keep
// it, so it is shown only once it is asked for: as a pair is generated, or worked
// out from the private key there is.
export const WireGuardFields = ({
    options,
    onChange,
    disabled = false,
    issue,
}: WireGuardFieldsProps) => {
    const privateKeyId = useId();
    const publicKeyId = useId();
    const peerKeyId = useId();
    const sharedKeyId = useId();
    const addressId = useId();
    const allowedId = useId();
    const mtuId = useId();
    const [publicKey, setPublicKey] = useState("");
    const [keyError, setKeyError] = useState<string>();

    const peer = peerOf(options);
    const privateKey = textOf(options.private_key);

    const setOption = (key: string, value: unknown) => onChange({ ...options, [key]: value });
    const setPeerOption = (key: string, value: unknown) =>
        onChange(withPeer(options, { [key]: value }));
    const validation = (path: string) => (issue?.path === path ? issue.message : undefined);

    const generateKeys = async () => {
        try {
            const pair = await generateKeypair("wireguard");

            setKeyError(undefined);
            setPublicKey(pair.publicKey ?? "");
            setOption("private_key", pair.privateKey ?? "");
        } catch (error) {
            setKeyError((error as Error).message);
        }
    };

    const derivePublicKey = async () => {
        try {
            const pair = await generateKeypair("wireguard", privateKey);

            setKeyError(undefined);
            setPublicKey(pair.publicKey ?? "");
        } catch (error) {
            setKeyError((error as Error).message);
        }
    };

    return (
        <div className="flex flex-col gap-2">
            <div className={ROW}>
                <div className={`${WIDE} flex items-center gap-4`}>
                    <FilledTextInput
                        id={privateKeyId}
                        label="Private key"
                        className="min-w-0 flex-1"
                        autoComplete="off"
                        spellCheck={false}
                        disabled={disabled}
                        validation={validation("private_key")}
                        value={privateKey}
                        onChange={(event) => {
                            // The public key shown was the old one's.
                            setPublicKey("");
                            setOption("private_key", event.target.value);
                        }}
                    />
                    <IconButton
                        icon={<KeyRegular size={20} />}
                        aria-label="Generate a WireGuard key pair"
                        variant="invisible"
                        disabled={disabled}
                        className={FIELD_ACTION}
                        onClick={() => void generateKeys()}
                    />
                </div>
                <div className={`${WIDE} flex items-center gap-4`}>
                    <FilledTextInput
                        id={publicKeyId}
                        label="Public key"
                        className="min-w-0 flex-1"
                        readOnly
                        value={publicKey}
                    />
                    <IconButton
                        icon={<ArrowClockwiseRegular size={20} />}
                        aria-label="Work out the public key"
                        variant="invisible"
                        disabled={disabled || !privateKey}
                        className={FIELD_ACTION}
                        onClick={() => void derivePublicKey()}
                    />
                </div>
                <FilledTextInput
                    id={peerKeyId}
                    label="Peer public key"
                    className={WIDE}
                    autoComplete="off"
                    spellCheck={false}
                    disabled={disabled}
                    validation={validation("peer_public_key")}
                    value={textOf(peer.public_key)}
                    onChange={(event) => setPeerOption("public_key", event.target.value)}
                />
                <FilledTextInput
                    id={sharedKeyId}
                    label="Pre-shared key"
                    className={WIDE}
                    autoComplete="off"
                    spellCheck={false}
                    disabled={disabled}
                    validation={validation("pre_shared_key")}
                    value={textOf(peer.pre_shared_key)}
                    onChange={(event) => setPeerOption("pre_shared_key", event.target.value)}
                />
                <FilledListField
                    id={addressId}
                    label="Local IPs (comma separated)"
                    className={WIDE}
                    separator=","
                    disabled={disabled}
                    validation={validation("address")}
                    value={options.address}
                    onChange={(addresses) => setOption("address", addresses)}
                />
            </div>

            {/* Cleared, the MTU leaves the options, and the core sends at its own
                default. */}
            <div className={ROW}>
                <FilledListField
                    id={allowedId}
                    label="Allowed IPs (comma separated)"
                    className={HALF}
                    separator=","
                    disabled={disabled}
                    validation={validation("allowed_ips")}
                    value={peer.allowed_ips}
                    onChange={(addresses) => setPeerOption("allowed_ips", addresses)}
                />
                <FilledTextInput
                    id={mtuId}
                    label="MTU"
                    className={FIELD}
                    type="number"
                    inputMode="numeric"
                    min={0}
                    disabled={disabled}
                    value={typeof options.mtu === "number" ? String(options.mtu) : ""}
                    onChange={(event) =>
                        setOption(
                            "mtu",
                            event.target.value === "" ? undefined : Number(event.target.value),
                        )
                    }
                />
            </div>

            {keyError && <InlineMessage variant="critical">{keyError}</InlineMessage>}
        </div>
    );
};
