-- Fixture for the migration loader's tests. Nothing runs this against a real
-- database; what is being checked is how the directory is read, so the SQL
-- only has to be plausible.

CREATE TABLE widgets (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text   NOT NULL
);

CREATE UNIQUE INDEX idx_widgets_name ON widgets (name);
