//go:build integration

package service

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/donaldturinglee/x-ui/internal/config"
	"github.com/donaldturinglee/x-ui/internal/database"
	"github.com/donaldturinglee/x-ui/internal/domain"
	"github.com/donaldturinglee/x-ui/internal/repository"
)

// The tests shadow every table the service uses with transaction-local TEMP
// tables. They never read or write the configured database's application data,
// and the outer transaction is always rolled back, including on test failure.
func outboundRenameTestStore(t *testing.T) *repository.Store {
	t.Helper()
	dir := os.Getenv("X_UI_TEST_CONFIG_DIR")
	if dir == "" {
		t.Skip("set X_UI_TEST_CONFIG_DIR to run PostgreSQL integration tests")
	}
	t.Setenv("X_UI_CONFIG_DIR", dir)
	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	db, err := database.Open(cfg.Database, false)
	if err != nil {
		t.Fatal(err)
	}
	tx := db.Begin()
	if tx.Error != nil {
		t.Fatal(tx.Error)
	}
	t.Cleanup(func() {
		tx.Rollback()
		database.Close(db)
	})
	// Explicitly exclude persistent schemas even if the configured connection
	// has a search_path that would otherwise put them ahead of pg_temp.
	if err := tx.Exec("SET LOCAL search_path TO pg_temp").Error; err != nil {
		t.Fatal(err)
	}
	for _, ddl := range []string{
		`CREATE TEMP TABLE outbounds (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type text NOT NULL, tag text NOT NULL UNIQUE, options jsonb) ON COMMIT DROP`,
		`CREATE TEMP TABLE inbounds (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type text NOT NULL, tag text NOT NULL UNIQUE, addrs jsonb, out_json jsonb, options jsonb) ON COMMIT DROP`,
		`CREATE TEMP TABLE settings (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, key text NOT NULL UNIQUE, value text NOT NULL) ON COMMIT DROP`,
		`CREATE TEMP TABLE stats (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, resource text NOT NULL, tag text NOT NULL, date_time bigint NOT NULL, direction boolean NOT NULL, traffic bigint NOT NULL, UNIQUE(resource,tag,date_time,direction)) ON COMMIT DROP`,
		`CREATE TEMP TABLE changes (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date_time bigint NOT NULL, actor text NOT NULL, key text NOT NULL, action text NOT NULL, obj jsonb) ON COMMIT DROP`,
	} {
		if err := tx.Exec(ddl).Error; err != nil {
			t.Fatal(err)
		}
	}
	return repository.NewStore(tx)
}

const renameTestBase = `{"route":{"final":"old","rules":[{"outbound":"old"}]},"dns":{"final":"old","servers":[{"tag":"old","detour":"old"}]}}`

func seedOutboundRename(t *testing.T, store *repository.Store) *domain.Outbound {
	t.Helper()
	ctx := context.Background()
	outbound := &domain.Outbound{Type: "socks", Tag: "old", Options: domain.JSON(`{"server":"old","server_port":1080,"password":"old"}`)}
	group := &domain.Outbound{Type: "selector", Tag: "group", Options: domain.JSON(`{"outbounds":["old"],"default":"old"}`)}
	inbound := &domain.Inbound{Type: "socks", Tag: "old", Options: domain.JSON(`{"detour":"old","tls":{"acme":{"http_client":{"detour":"old"}}}}`)}
	for _, err := range []error{
		store.Outbounds.Create(ctx, outbound),
		store.Outbounds.Create(ctx, group),
		store.Inbounds.Create(ctx, inbound),
		store.Settings.Set(ctx, domain.SettingCoreConfig, renameTestBase),
		store.Stats.AddSamples(ctx, []domain.Stat{
			{Resource: "outbound", Tag: "old", DateTime: 100, Direction: true, Traffic: 100},
			{Resource: "outbound", Tag: "new", DateTime: 100, Direction: true, Traffic: 40},
			{Resource: "inbound", Tag: "old", DateTime: 100, Direction: true, Traffic: 77},
		}),
	} {
		if err != nil {
			t.Fatal(err)
		}
	}
	return outbound
}

func TestOutboundRenameIntegration(t *testing.T) {
	store := outboundRenameTestStore(t)
	outbound := seedOutboundRename(t, store)
	outbound.Tag = "new"
	outbound.Options = domain.JSON(`{"server":"changed.example.com","server_port":1081,"password":"old"}`)
	if err := NewOutboundService(store).Update(context.Background(), "operator", outbound); err != nil {
		t.Fatal(err)
	}
	saved, err := store.Outbounds.FindById(context.Background(), outbound.Id)
	if err != nil || saved.Tag != "new" || canonicalJSON(t, string(saved.Options)) != canonicalJSON(t, string(outbound.Options)) {
		t.Fatalf("saved outbound = %+v, %v", saved, err)
	}
	assertRenameDependents(t, store, "new", 140)
	// Maintenance avoids client tables: the generated route still has to use
	// the renamed outbound and its updated base document together.
	if err := store.Settings.Set(context.Background(), domain.SettingMaintenance, "true"); err != nil {
		t.Fatal(err)
	}
	generated, err := NewConfigService(store, NewSettingService(store), NewInboundService(store), NewOutboundService(store)).Generate(context.Background())
	if err != nil || !generated.Maintenance {
		t.Fatalf("generated config = %+v, %v", generated, err)
	}
	changes, err := store.Stats.ListChanges(context.Background(), repository.ChangeFilter{})
	if err != nil || len(changes) != 1 || changes[0].Key != "outbounds" || changes[0].Actor != "operator" {
		t.Fatalf("audit = %+v, %v", changes, err)
	}
}

func TestConfigSnapshotIntegration(t *testing.T) {
	dir := os.Getenv("X_UI_TEST_CONFIG_DIR")
	if dir == "" {
		t.Skip("set X_UI_TEST_CONFIG_DIR to run PostgreSQL integration tests")
	}
	t.Setenv("X_UI_CONFIG_DIR", dir)
	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	db, err := database.Open(cfg.Database, false)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { database.Close(db) })
	// Query transaction metadata only, without reading application tables.
	err = repository.NewStore(db).ReadSnapshot(context.Background(), func(tx *repository.Store) error {
		var isolation, readOnly string
		if err := tx.DB().Raw("SHOW transaction_isolation").Scan(&isolation).Error; err != nil {
			return err
		}
		if err := tx.DB().Raw("SHOW transaction_read_only").Scan(&readOnly).Error; err != nil {
			return err
		}
		if isolation != "repeatable read" || readOnly != "on" {
			t.Errorf("snapshot transaction = %q, read only %q", isolation, readOnly)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestOutboundRenameIntegrationRejectsDuplicate(t *testing.T) {
	store := outboundRenameTestStore(t)
	outbound := seedOutboundRename(t, store)
	outbound.Tag = "group"
	if err := NewOutboundService(store).Update(context.Background(), "operator", outbound); !errors.Is(err, domain.ErrConflict) {
		t.Fatalf("duplicate rename = %v", err)
	}
	assertRenameDependents(t, store, "old", 100)
}

func TestOutboundRenameIntegrationRollsBackAllChanges(t *testing.T) {
	store := outboundRenameTestStore(t)
	outbound := seedOutboundRename(t, store)
	// Fail after reference, history, and outbound writes have all succeeded.
	if err := store.DB().Exec(`ALTER TABLE pg_temp.changes ADD CONSTRAINT reject_edit CHECK (action <> 'edit')`).Error; err != nil {
		t.Fatal(err)
	}
	outbound.Tag = "new"
	if err := NewOutboundService(store).Update(context.Background(), "operator", outbound); err == nil {
		t.Fatal("rename succeeded despite the failed audit write")
	}
	saved, err := store.Outbounds.FindById(context.Background(), outbound.Id)
	if err != nil || saved.Tag != "old" {
		t.Fatalf("outbound was not rolled back: %+v, %v", saved, err)
	}
	assertRenameDependents(t, store, "old", 100)
}

func assertRenameDependents(t *testing.T, store *repository.Store, tag string, traffic int64) {
	t.Helper()
	ctx := context.Background()
	base, err := store.Settings.Get(ctx, domain.SettingCoreConfig)
	want := `{"route":{"final":"` + tag + `","rules":[{"outbound":"` + tag + `"}]},"dns":{"final":"old","servers":[{"tag":"old","detour":"` + tag + `"}]}}`
	if err != nil || canonicalJSON(t, base) != canonicalJSON(t, want) {
		t.Fatalf("base = %s, %v", base, err)
	}
	group, err := store.Outbounds.FindByTag(ctx, "group")
	want = `{"outbounds":["` + tag + `"],"default":"` + tag + `"}`
	if err != nil || canonicalJSON(t, string(group.Options)) != canonicalJSON(t, want) {
		t.Fatalf("group = %+v, %v", group, err)
	}
	inbound, err := store.Inbounds.FindByTag(ctx, "old")
	want = `{"detour":"old","tls":{"acme":{"http_client":{"detour":"` + tag + `"}}}}`
	if err != nil || canonicalJSON(t, string(inbound.Options)) != canonicalJSON(t, want) {
		t.Fatalf("inbound = %+v, %v", inbound, err)
	}
	samples, err := store.Stats.Query(ctx, []string{"outbound"}, tag, 0, 200)
	if err != nil || len(samples) != 1 || samples[0].Traffic != traffic {
		t.Fatalf("outbound traffic = %+v, %v", samples, err)
	}
	samples, err = store.Stats.Query(ctx, []string{"inbound"}, "old", 0, 200)
	if err != nil || len(samples) != 1 || samples[0].Traffic != 77 {
		t.Fatalf("inbound traffic changed = %+v, %v", samples, err)
	}
}
